# -*- coding: utf-8 -*-
"""Tabel data lpescan — displice ke dist/lpescan.py oleh build-scanner.py.
HANYA berisi literal data, tanpa import/dokumen panjang."""

# dpkg/rpm package name (fnmatch) -> [(vendor, product)] CPE
PKG_TO_CPE = {
    "sudo":            [("todd_miller", "sudo"), ("sudo_project", "sudo")],
    "libc6":           [("gnu", "glibc")],
    "glibc":           [("gnu", "glibc")],
    "libc6-*":         [("gnu", "glibc")],
    "bash":            [("gnu", "bash")],
    "coreutils":       [("gnu", "coreutils")],
    "util-linux":      [("andries_brouwer", "util-linux"), ("kernel", "util-linux")],
    "policykit-1":     [("polkit_project", "polkit")],
    "polkitd":         [("polkit_project", "polkit")],
    "polkit":          [("polkit_project", "polkit")],
    "snapd":           [("canonical", "snapd")],
    "apport":          [("canonical", "apport")],
    "python-apport":   [("canonical", "apport")],
    "dbus":            [("freedesktop", "libdbus")],
    "dbus-daemon":     [("freedesktop", "libdbus")],
    "libdbus-1-*":     [("freedesktop", "libdbus")],
    "openssl":         [("openssl", "openssl")],
    "libssl*":         [("openssl", "openssl")],
    "libcrypto*":      [("openssl", "openssl")],
    "perl":            [("perl", "perl")],
    "perl-base":       [("perl", "perl")],
    "perl-*":          [("perl", "perl")],
    "python3*":        [("python", "python")],
    "python2*":        [("python", "python")],
    "python-*":        [("python", "python")],
    "rpm":             [("rpm", "rpm")],
    "rpm-libs":        [("rpm", "rpm")],
    "xen*":            [("xen", "xen")],
    "qemu*":           [("qemu", "qemu")],
    "openldap":        [("openldap", "openldap")],
    "slapd":           [("openldap", "openldap")],
    "libldap*":        [("openldap", "openldap")],
    "postgresql":      [("postgresql", "postgresql")],
    "postgresql-*":    [("postgresql", "postgresql"), ("debian", "postgresql-common")],
    "samba":           [("samba", "samba")],
    "smbd":            [("samba", "samba")],
    "samba-common":    [("samba", "samba")],
    "rsync":           [("samba", "rsync")],
    "cifs-utils":      [("samba", "cifs-utils")],
    "zlib1g":          [("zlib", "zlib")],
    "zlib":            [("zlib", "zlib")],
    "libexpat1":       [("libexpat_project", "libexpat")],
    "expat":           [("libexpat_project", "libexpat")],
    "libxml2":         [("xmlsoft", "libxml2")],
    "libxml2-*":       [("xmlsoft", "libxml2")],
    "libssh*":         [("libssh", "libssh")],
    "sqlite3":         [("sqlite", "sqlite")],
    "libsqlite3*":     [("sqlite", "sqlite")],
    "systemd":         [("systemd_project", "systemd")],
    "systemd-*":       [("systemd_project", "systemd")],
    "cups*":           [("apple", "cups"), ("linuxfoundation", "cups-filters")],
    "apache2":         [("apache", "http_server")],
    "httpd":           [("apache", "http_server")],
    "tomcat*":         [("apache", "tomcat")],
    "nginx*":          [("nginx", "nginx"), ("f5", "nginx")],
    "firefox":         [("mozilla", "firefox")],
    "firefox-*":       [("mozilla", "firefox")],
    "thunderbird":     [("mozilla", "thunderbird")],
    "curl":            [("haxx", "curl")],
    "libcurl*":        [("haxx", "libcurl"), ("haxx", "curl")],
    "wget":            [("gnu", "wget")],
    "tar":             [("gnu", "tar")],
    "gawk":            [("gnu", "gawk")],
    "findutils":       [("gnu", "findutils")],
    "screen":          [("gnu", "screen"), ("juergen", "weigert_screen")],
    "tmux":            [("nicholas_marriott", "tmux")],
    "procps":          [("procps-ng_project", "procps-ng")],
    "procps-ng":       [("procps-ng_project", "procps-ng")],
    "openssh*":        [("openbsd", "openssh")],
    "openssh-server":  [("openbsd", "openssh")],
    "openssh-client":  [("openbsd", "openssh")],
    "bind9*":          [("isc", "bind")],
    "bind":            [("isc", "bind")],
    "krb5-*":          [("eyrie", "pam-krb5")],
    "libpam-krb5":     [("eyrie", "pam-krb5")],
    "shadow":          [("shadow_project", "shadow"), ("suse", "shadow")],
    "login":           [("shadow_project", "shadow")],
    "passwd":          [("shadow_project", "shadow")],
    "exim4*":          [("exim", "exim"), ("university_of_cambridge", "exim")],
    "postfix":         [("postfix", "postfix")],
    "sendmail*":       [("sendmail", "sendmail"), ("eric_allman", "sendmail")],
    "dovecot*":        [("dovecot", "dovecot")],
    "proftpd*":        [("proftpd", "proftpd"), ("proftpd_project", "proftpd")],
    "pure-ftpd*":      [("pureftpd", "pure-ftpd")],
    "lighttpd":        [("lighttpd", "lighttpd")],
    "php*":            [("php", "php")],
    "expect":          [("don_libes", "expect")],
    "policycoreutils": [("redhat", "policycoreutils")],
    "language-selector*": [("ubuntu", "language-selector")],
}

# distro id (/etc/os-release ID) -> [(vendor, product)] CPE untuk pin distro
DISTRO_TO_CPE = {
    "debian":        [("debian", "debian_linux")],
    "ubuntu":        [("canonical", "ubuntu_linux")],
    "fedora":        [("fedoraproject", "fedora")],
    "rhel":          [("redhat", "enterprise_linux_server"),
                      ("redhat", "enterprise_linux_desktop"),
                      ("redhat", "enterprise_linux_workstation")],
    "redhat":        [("redhat", "enterprise_linux_server")],
    "centos":        [("redhat", "enterprise_linux_server")],
    "opensuse-leap": [("opensuse", "leap")],
    "opensuse":      [("opensuse", "opensuse")],
    "sles":          [("suse", "suse_linux")],
    "kali":          [("debian", "debian_linux")],
}

# Windows: release token (huruf kecil, tanpa 'windows_') -> build number dasar
WIN_RELEASE_TO_BUILD = {
    "windows_10": {
        "1507": 10240, "1511": 10586, "1607": 14393, "1703": 15063,
        "1709": 16299, "1803": 17134, "1809": 17763, "1903": 18362,
        "1909": 18363, "2004": 19041, "20h2": 19042, "21h1": 19043,
        "21h2": 19044, "22h2": 19045,
    },
    "windows_11": {
        "21h2": 22000, "22h2": 22621, "23h2": 22631,
        "24h2": 26100, "25h2": 26100, "26h1": 26100,
    },
    "windows_server_2008": {"sp2": 6002},
    "windows_server_2008_r2": {"sp1": 7601},
    "windows_server_2012": {"": 9200},
    "windows_server_2012_r2": {"": 9600},
    "windows_server_2016": {"1607": 14393, "1809": 17763, "1903": 18362, "1909": 18363},
    "windows_server_2019": {"1809": 17763, "1903": 18362, "1909": 18363},
    "windows_server_2022": {"21h2": 20348},
    "windows_server_2022_23h2": {"23h2": 25398},
    "windows_server_2025": {"24h2": 26100},
    "windows_7": {"sp1": 7601},
    "windows_8.1": {"": 9600},
    "windows_rt_8.1": {"": 9600},
}

# basename (fnmatch, lowercase) biner SUID yang dikenal berbahaya (GTFOBins-style)
GTFO_SUIDS = [
    "find", "vim*", "nano", "less", "more", "awk", "gawk", "python*", "perl",
    "ruby*", "php*", "bash", "dash", "sh", "zsh", "env", "cp", "mv", "tar",
    "unzip", "zip", "ssh", "scp", "sftp", "curl", "wget", "socat", "nc",
    "ncat", "pkexec", "mount", "umount", "fusermount*", "su", "ping", "ping6",
    "passwd", "chsh", "chfn", "newgrp", "gpasswd", "sudoedit", "tcpdump",
    "capsh", "setcap", "getcap", "systemctl", "journalctl", "busctl", "crontab",
    "at", "flock", "comm", "csplit", "cut", "diff", "expand", "fmt", "fold",
    "head", "join", "nl", "od", "paste", "pr", "sed", "sort", "split", "tail",
    "tee", "tr", "uniq", "xxd", "base64", "openssl", "date", "timeout", "watch",
    "node*", "lua*", "ruby*", "cpan", "gdb", "strace", "taskset", "chroot",
    "nsenter", "unshare", "bwrap", "rpm", "dpkg", "apt*", "dockerd", "docker",
    "runuser", "pkill", "pgrep", "ps", "top", "htop", "ionice", "nice", "nohup",
    "printf", "echo", "sleep", "uptime", "w", "who", "id", "groups", "csh",
    "ksh", "expect", "screen", "tmux", "script", "mail", "mutt", "git", "hg",
    "svn", "rsh", "rlogin", "tclsh*", "wish*", "dbus*", "gcore", "javac", "java",
]

# privilege Windows yang menarik + saran exploit
WIN_INTERESTING_PRIVS = {
    "SeImpersonatePrivilege": "Potato family (JuicyPotato/PrintSpoofer/GodPotato)",
    "SeAssignPrimaryTokenPrivilege": "Potato family (JuicyPotato/PrintSpoofer)",
    "SeBackupPrivilege": "robocopy /b atau reg save SAM/SYSTEM + secretsdump",
    "SeRestorePrivilege": "tulis file sistem (ganti driver/service binary)",
    "SeDebugPrivilege": "injeksi ke proses SYSTEM (mimikatz / token steal)",
    "SeTakeOwnershipPrivilege": "ambil kepemilikan file sistem lalu modifikasi",
    "SeLoadDriverPrivilege": "load driver rentan (Capcom / BYOVD)",
    "SeCreateTokenPrivilege": "buat token sendiri (potensi SYSTEM)",
    "SeTcbPrivilege": "bertindak sebagai bagian OS (setara SYSTEM)",
    "SeEnableDelegationPrivilege": "delegasi token (relay/kerberoast vector)",
}
